### ISSUE TITLE
Windows: lasview can't find file on system selected by file explorer

### ISSUE THREAD

**Issue by chrisranderson** [rapidlasso/LAStoolsPluginQGIS3#2]
I'm trying to view a .las file with LAStools. I used ctrl+k to find `lasview`, and I use the file browser to pick a file, so the path is correct, but it says the path is not found. I'm using Windows, LAStools 1.0, and QGIS 3.2.2.

```
LAStools command line
C:\LAStools\bin\lasview -i "C:/Users/my_user/home/projects/lidar_exploration/las_data/sample_file.las" -points 5000000
LAStools console output
The system cannot find the path specified. 
```

**Comment by chrisranderson** [comment]
I also noticed lasviewPro mixes forward and backward slashes: `C:\LAStools\bin\lasview -v -gui -i C:/Users/my_user/home/projects/lidar_exploration/las_data\*.las -points 5000000`

**Comment by rapidlasso** [comment]
Do you have [LAStools ](http://rapidlasso.com/LAStools) installed on the C:\ drive? The LAStools plugin in QGIS does not include the actual [LAStools ](http://rapidlasso.com/LAStools) software but just the scripts that create the toolboxes and call the [LAStools ](http://rapidlasso.com/LAStools) modules that needs to be downloaded from [LAStools ](http://rapidlasso.com/LAStools).

**Comment by chrisranderson** [comment]
Oh, no. Maybe add that as a warning somewhere; is it possible to install LAStools as part of the plugin installation (I'm guessing not)? Seems unusual that installing a plugin requires additional steps before it works. I was thinking it was something wrong with the path I was providing. I'll try that.

**Comment by chrisranderson** [comment]
That worked, thank you. I'm not really seeing how integration works, though, since `lasview` opens the .las file in a viewer, not as part of the QGIS project.

**Comment by rapidlasso** [comment]
I'll add a warning in the next release.
