### ISSUE TITLE
Proper location of LAStools

### ISSUE THREAD

**Issue by mhkeller** [rapidlasso/LAStoolsPluginQGIS3#3]
After I download LAStools from [here](https://rapidlasso.com/lastools/) where do I put this folder so it's accessible to QGIS's path? I added that folder to my system path but when I try to run `las2shp` I get the following output showing that it's looking for it in `C:` but I'm on MacOS

```
LAStools command line
C:\LAStools/bin/las2shp -v -gui -i "/Users/me/Downloads/file.las"
LAStools console output
/bin/sh: C:LAStools/bin/las2shp: No such file or directory
```

`las2shp` is available from my command line, however.

**Comment by rapidlasso** [comment]
By default the variable in the QGIS Processing points to "C:\LAStools" and you need to change it to point to the directory where your LAStools installation is stored. See the screenshot below.

When you run on a MacOS you **in addition** also need to install WinE and provide the PATH to the WinE executable for all non-open source LAStools that are only available as Windows *.exe binaries.

![lastools_qgis_processing_toolbox_options](https://user-images.githubusercontent.com/1107656/46871690-600dbd80-ce32-11e8-81a2-61f1415861b8.png)
