### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 5: invalid start byte

### ISSUE THREAD

**Issue by ChristianDonaldson** [rapidlasso/LAStoolsPluginQGIS3#4]
LAStoolsUtils.runLAStools(commands, feedback)
File "C:/Users/chdo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStoolsUtils.py", line 61, in runLAStools
feedback.pushConsoleInfo(output.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 5: invalid start byte

**Comment by rapidlasso** [comment]
Has this been resolved? There was not enough information given. Old version?
