### ISSUE TITLE
LAStools is not working | QGIS Desktop 3.12.3 | Win10

### ISSUE THREAD

**Issue by migueljsmorais** [rapidlasso/LAStoolsPluginQGIS3#9]
Versão do QGIS: 3.12.3-București
Código de revisão do QGIS: 8234261527
Versão do Qt: 5.11.2
Versão do GDAL: 3.0.4
Versão do GEOS: 3.8.1-CAPI-1.13.3
Versão do PROJ: Rel. 6.3.2, May 1st, 2020
A processar o algoritmo...
Algoritmo 'lasinfo' starting…
Parâmetros de entrada:
{ 'ADDITIONAL_OPTIONS' : '', 'COMPUTE_DENSITY' : False, 'CPU64' : False, 'GUI' : False, 'HISTO1' : 0, 'HISTO1_BIN' : 1, 'HISTO2' : 0, 'HISTO2_BIN' : 1, 'HISTO3' : 0, 'HISTO3_BIN' : 1, 'INPUT_LASLAZ' : 'C:\\Users\\Miguel Morais\\Downloads\\nd_lidar.las', 'REPAIR_BB' : False, 'REPAIR_COUNTERS' : False, 'VERBOSE' : False }

LAStools command line
C:/Users/Miguel Morais/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/LAStools\bin\lasinfo -i "C:\Users\Miguel Morais\Downloads\nd_lidar.las"
LAStools console output
'C:/Users/Miguel' is not recognized as an internal or external command, 
operable program or batch file. 

Execução completa em 0.08 segundos
Resultados:
{'': None}

A carregar as camadas resultantes
Algoritmo 'lasinfo' terminado

**Comment by rapidlasso** [comment]
Hello,

Where did you install the LAStools software? In this directory???

C:/Users/Miguel Morais/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/LAStools

I have the feeling you only installed the QGIS plugin but not the actual LAStools software yet?

Also ... please DO NOT USE SPACES in PATH or FILE names.

C:/Users/Miguel Morais/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/LAStools\bin\lasinfo

The space in "Miguel Morais" may cause problems also for other (Python) applications.

**Comment by migueljsmorais** [comment]
> Hello,
> 
> Where did you install the LAStools software? In this directory???
> 
> C:/Users/Miguel Morais/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/LAStools
> 
> I have the feeling you only installed the QGIS plugin but not the actual LAStools software yet?
> 
> Also ... please DO NOT USE SPACES in PATH or FILE names.
> 
> C:/Users/Miguel Morais/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/LAStools\bin\lasinfo
> 
> The space in "Miguel Morais" may cause problems also for other (Python) applications.

I only installed the QGIS plugin, so it's fixed already, but now I'm having a different problem, when I inspect the .las file the points are all unclassified, is that a problem I can fix or is it a incompetence problem on my provider end?

**Comment by rapidlasso** [comment]
This is no longer an issue to be discussed here, but [maybe here instead](https://groups.google.com/d/forum/lastools).
